<Project>
  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.csproj'">
    <BaseOutputPath>$(MSBuildThisFileDirectory)tmp\build\dotnet\bin\$(MSBuildProjectName)\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)tmp\build\dotnet\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
